faiss_db:
  collection_name: "DMP-RAG"

embedding_model:
  provider: ollama
  model_name: nomic-embed-text

llm:
  llama3.3:
    provider: ollama
    model_name: llama3.3
    api_base_url: http://localhost:11434
    temperature: 0.2
    max_output_tokens: 2048

