faiss_db:
  collection_name: "DMP-RAG"

embedding_model:
  provider: "ollama"                 # Local embeddings through Ollama
  model_name: "nomic-embed-text"     # Or try: "mxbai-embed-large"
  api_base_url: "http://localhost:11434"
  batch_size: 32
  normalize_embeddings: true

retriever:
  top_k: 10

llm:
  llama3.3:
    provider: "ollama"
    model_name: "llama3.3"
    api_base_url: "http://localhost:11434"
    temperature: 0.1
    max_output_tokens: 2048

  llama4:
    provider: "ollama"
    model_name: "llama4"
    api_base_url: "http://localhost:11434"
    temperature: 0.1
    max_output_tokens: 2048
